export { Route, Routes } from "react-router-dom";
export { ErrorView } from "@/views/ErrorView";
export { GenreView } from "@/views/genre/GenreView";
export * from "@/views/site/HomeView";
export { HomeView } from "@/views/site/HomeView";
export { MainLayout } from "../layouts/MainLayout";
export { ImagesView } from "./media/ImagesView";
export { MoviesView } from "./media/Movies/MoviesView";
export { MovieView } from "./media/Movies/MovieView";
export { TrendingView } from "./media/Movies/TrendingView";
export { ReviewsView } from "./media/ReviewsView";
export { TrailerView } from "./media/TrailerView";
export { EpisodesView } from "./media/TV/EpisodesView";
export { SeasonsView } from "./media/TV/SeaonsView";
export { TelevisionView } from "./media/TV/TelevisionView";
export { ViewTV } from "./media/TV/ViewTV";
export { CareerView } from "./people/CareerView";
export { CreditsView } from "./people/CreditsView";
export { PersonView } from "./people/PersonView";
export { SearchView } from "./Search/SearchView";
export { FavoritesView } from "./people/FavouritesView";
export { SettingsView } from "./people/SettingsView";
export { CartView } from "./people/CartView";
