export { Route, Routes } from "react-router-dom";
export { ErrorView } from "@/views/ErrorView";
export { GenreView } from "@/views/Genre/GenreView";
export * from "@/views/site/HomeView";
export { HomeView } from "@/views/site/HomeView";
export { MainLayout } from "../layouts/MainLayout";
export { ImagesView } from "./Media/ImagesView";
export { MoviesView } from "./Media/Movies/MoviesView";
export { MovieView } from "./Media/Movies/MovieView";
export { TrendingView } from "./Media/Movies/TrendingView";
export { ReviewsView } from "./Media/ReviewsView";
export { TrailerView } from "./Media/TrailerView";
export { EpisodesView } from "./Media/TV/EpisodesView";
export { SeasonsView } from "./Media/TV/SeaonsView";
export { TelevisionView } from "./Media/TV/TelevisionView";
export { ViewTV } from "./Media/TV/ViewTV";
export { CareerView } from "./People/CareerView";
export { CreditsView } from "./People/CreditsView";
export { PersonView } from "./People/PersonView";
export { SearchView } from "./Search/SearchView";
